Repository lablup/raftify, pull requests merged in 2024-09, with the labels that each got.

#111 feat: Add an option to ignore logs about heartbeat message
  .gitignore
  Cargo.lock
  harness/src/config.rs
  raftify/Cargo.toml
  raftify/src/raft_node/mod.rs
Labels: feature

#125 feat: Add logging level to python bindings
  binding/python/raftify.pyi
  binding/python/src/bindings/slogger.rs
  binding/python/src/lib.rs
Labels: feature, python

#106 ci: Improve pypi package release workflow
  .github/workflows/deployment-pypi.yml
  .gitignore
Labels: ci

#108 fix: Cargo test failure in Windows environment
  harness/src/utils.rs
Labels: test

#129 feat: Add pre-commit hooks for code formatting, linting
  .pre-commit-config.yaml
  DEVELOPMENT.md
  raftify/src/raft_node/mod.rs
Labels: ci

#137 feat: Add `omit_heartbeat_log` parameter for python binding
  binding/python/raftify.pyi
  binding/python/src/bindings/raft_rs/config.rs
Labels: feature, python
